version: "3.4"

services:
  ifconfig:
    image: ip123.top:latest
    #image: georgyo/ifconfig.io:latest
    build:
      context: ./
      target: production
    ports:
      - ${PORT:-80}:80
      - ${TSLPORT:-443}:443
    environment:
      TLS: ${TLS:-1}
      HOSTNAME: ${HOSTNAME}
